services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres_wallet
    restart: always
    environment:
      - 'POSTGRES_DB=wallet_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'

  redis:
    image: 'redis:latest'
    container_name: redis-cache-pay
    ports:
      - '6379'